### ISSUE TITLE
Deploy testnet warp routes to test the rebalancer

### ISSUE THREAD

**Issue by fzavalia** [BootNodeDev/hyperlane-monorepo#48]
Deploy a USDC warp route for arbitrum, sepolia, optimism, mode testnets. The first three should be collaterals while the last synthetic.

Deploy a secondary warp route used as bridge for arbitrum, sepolia and optimism. All collaterals

**Comment by fzavalia** [comment]
### Primary Warp Route:

_~/.hyperlane/deployments/warp_routes/USDC/arbitrumsepolia-modetestnet-optimismsepolia-sepolia-config.yaml_

```yaml
# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760"
    chainName: arbitrumsepolia
    collateralAddressOrDenom: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
    connections:
      - token: ethereum|modetestnet|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|optimismsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|sepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760"
    chainName: modetestnet
    connections:
      - token: ethereum|arbitrumsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|optimismsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|sepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
    decimals: 6
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760"
    chainName: optimismsepolia
    collateralAddressOrDenom: "0x5fd84259d66Cd46123540766Be93DFE6D43130D7"
    connections:
      - token: ethereum|arbitrumsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|modetestnet|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|sepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760"
    chainName: sepolia
    collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    connections:
      - token: ethereum|arbitrumsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|modetestnet|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|optimismsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
```

### Nested Warp Route

_~/.hyperlane/deployments/warp_routes/USDC/arbitrumsepolia-optimismsepolia-sepolia-config.yaml_

```yaml
# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x65C418813af18A847d32239bd50393460238f62e"
    chainName: arbitrumsepolia
    collateralAddressOrDenom: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
    connections:
      - token: ethereum|optimismsepolia|0x65C418813af18A847d32239bd50393460238f62e
      - token: ethereum|sepolia|0x65C418813af18A847d32239bd50393460238f62e
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x65C418813af18A847d32239bd50393460238f62e"
    chainName: optimismsepolia
    collateralAddressOrDenom: "0x5fd84259d66Cd46123540766Be93DFE6D43130D7"
    connections:
      - token: ethereum|arbitrumsepolia|0x65C418813af18A847d32239bd50393460238f62e
      - token: ethereum|sepolia|0x65C418813af18A847d32239bd50393460238f62e
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x65C418813af18A847d32239bd50393460238f62e"
    chainName: sepolia
    collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    connections:
      - token: ethereum|arbitrumsepolia|0x65C418813af18A847d32239bd50393460238f62e
      - token: ethereum|optimismsepolia|0x65C418813af18A847d32239bd50393460238f62e
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
```
